### ISSUE TITLE
Tool tip when mouse over area?

### ISSUE THREAD

**Issue by borysr** [coldiary/react-image-mapper#11]
Great package, thanks!.
Is there way to add "tip" message for the hover over the area ?

**Comment by coldiary** [comment]
This is a feature request I presumed.

So before I dive into adding this, would you mind answering these specs interrogation for me :
- How much of a customization do you need ?
  - Do you want to define styling, like color, background, shape, shadow, with an arrow ?
- How about placement ?
  - Do you need an option to define placement ?
  - Does the tip need to follow the mouse ?
- How about a delay ? Or a transition/animation ?
- Do you want to avoid external library to handle of these ?
- Lastly, do you prefer a way to customize the rendering of any component onHover of a region ?

Every one of these should be possible to implement in user land, as you get coords in enter/leave methods but I could consider adding this option.

**Comment by borysr** [comment]
Thanks for the quick reply. 
That was rather a question than a feature request  ( definitely not an issue). I was not sure where to post it. 
I am not very "seasoned" front end developer, so If there is a way to do it in "user land" would you please just  point me to right direction?

**Comment by coldiary** [comment]
Okay I see, so what you could do in order to have a tip hovering the highlighted area is to : 
1. Have the component wrapped inside a container with `position: relative` (in ordre to position the tip afterwards)
2. Have an element to be the tip, _let's say a styled div_, next to the component
3. Have it be conditionally rendered wether you are hovering an area (this can be a prop in state, to be set and unset in the enter/leave methods)
4. update his absolute position according to the hovered area coordinates (like the centroid for example) with : 
```css
{
    position: absolute;
    top: // y_center;
    left: // x_center;
}
```

I'll update the comment with a complete example.

**Comment by borysr** [comment]
Great, Thanks!

**Comment by coldiary** [comment]
I updated the demo page with a complete example, I hope it suits your need.

**Comment by borysr** [comment]
Thanks a lot!

**Comment by ReactRS** [comment]
The tooltip does is not displayed?  If i replace the <span> with <p> i see the name displayed right below the  image map loaded. Any idea why?
